project:
  type: book
  output-dir: ../docs


book:
  title: "My Recipes"
  author: "Angel Alcala Ruiz"
  date: "10/16/2024"
  chapters:
    - index.qmd
    - part: "COOKING"
      chapters: 
        - garlic-mushrooms.qmd
    - part: "COOKIES"
      chapters: 
        - chocolate-chip-cookies.qmd
        - cream-cheese-cookies.qmd
        - double-chocolate-chip-cookies.qmd
        - oatmeal-raisin-cookies.qmd
    - part: "BARS & CAKES"
      chapters: 
        - pumpkin-bars.qmd
        - tres-leches.qmd
    - part: "BREADS"
      chapters:
        - pumpkin-bread.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt



